/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.shawarma.smsgateway;

public final class R {
  public static final class drawable {
    public static final int bg_button_blue=0x7f010000;
    public static final int bg_button_green=0x7f010001;
    public static final int bg_button_outline=0x7f010002;
    public static final int bg_button_outline_light=0x7f010003;
    public static final int bg_button_red=0x7f010004;
    public static final int bg_card_dark=0x7f010005;
    public static final int bg_card_light=0x7f010006;
    public static final int bg_edit_text=0x7f010007;
    public static final int bg_edit_text_light=0x7f010008;
    public static final int bg_pill_amber=0x7f010009;
    public static final int bg_pill_gray=0x7f01000a;
    public static final int bg_pill_gray_light=0x7f01000b;
    public static final int bg_pill_green=0x7f01000c;
    public static final int bg_pill_red=0x7f01000d;
    public static final int ic_bell_line=0x7f01000e;
    public static final int ic_call_line=0x7f01000f;
    public static final int ic_customers_line=0x7f010010;
    public static final int ic_dashboard_line=0x7f010011;
    public static final int ic_edit_line=0x7f010012;
    public static final int ic_launcher_dukandar=0x7f010013;
    public static final int ic_menu_line=0x7f010014;
    public static final int ic_offers_line=0x7f010015;
    public static final int ic_orders_line=0x7f010016;
    public static final int ic_plus_line=0x7f010017;
    public static final int ic_refresh_line=0x7f010018;
    public static final int ic_reviews_line=0x7f010019;
    public static final int ic_search_line=0x7f01001a;
    public static final int ic_settings_line=0x7f01001b;
    public static final int ic_sim_line=0x7f01001c;
    public static final int ic_star_line=0x7f01001d;
    public static final int ic_theme_line=0x7f01001e;
    public static final int ic_trash_line=0x7f01001f;
  }
  public static final class string {
    public static final int app_name=0x7f020000;
  }
}